version: '3'
services:
  api:
    image: registry.gitlab.com/frondor/restful-api:latest
    environment:
      - NODE_ENV=production
    ports:
      - 3000

  nginx:
    environment:
      - VIRTUAL_HOST=domain.com