version: '3'
services:

  api:
    container_name: api
    depends_on:
      - database
      - redis
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.13.12-alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
      - REST_API_HOST=api # compose service name
    volumes:
      - ./nginx/config:/opts/nginx/config
      - ./nginx/start-nginx.sh:/opts/nginx/start-nginx.sh
      - ./nginx/certs:/etc/ssl/certs
    command: sh /opts/nginx/start-nginx.sh
    restart: unless-stopped

  database:
    container_name: database
    image: mariadb:10.3.6
    ports:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:3.2.11-alpine
    ports:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
