version: '3'
services:

  restful_api:
    volumes:
      - ./restful-api:/home/node/api
      - /home/node/api/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - APP_URL=http://0.0.0.0:3000
      - APP_KEY=xOrVHYdzLA3QuZyvjQFcfMG6MRVAUrdl
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=project
      - REDIS_CONNECTION=local
    command: sh -c './wait-for-db.sh database:3306 -- adonis migration:run && adonis serve --dev -p'

  database:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=project

  nginx:
    volumes:
      - ./nginx/nginx-app.template:/etc/nginx/conf.d/nginx-app.template
      - ./nginx/certs:/etc/ssl/certs