version: '3'
services:

  api:
    build: ./restful-api
    volumes:
      - ./restful-api:/home/node/api
      - /home/node/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - minio
    env_file:
      - ./restful-api/dev.env
    command: sh -c './wait-for-db.sh database:3306 -- adonis migration:run && adonis serve --dev -p'

  database:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=project

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=FAKE_S3
      - MINIO_SECRET_KEY=FAKE_S3_key
    volumes:
      - minio_data:/export
      # - /mnt/export:/export
      # - /mnt/config:/root/.minio
    entrypoint: sh
    command: -c 'mkdir -p /export/app-pics && /usr/bin/minio server /export'

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 FAKE_S3 FAKE_S3_key;
      /usr/bin/mc mb myminio/app-pics;
      /usr/bin/mc policy download myminio/app-pics;
      exit 0;
      "

  nginx:
    environment:
      - VIRTUAL_HOST=dev.local
      - S3_PROXY_PASS=http://minio:9000/app-pics/

volumes:
  minio_data: