version: '3'
services:
  restful_api:
    container_name: restful_api
    build: ./restful-api
    ports:
      - "3000"
    restart: unless-stopped
    environment:
      - ENV_SILENT=true
  nginx:
    container_name: webserver
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - restful_api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/nginx-app.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
