version: '3'
services:

  restful_api:
    volumes:
      - ./restful-api:/home/node/api
      - /home/node/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - minio
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - APP_URL=http://0.0.0.0:3000
      - APP_KEY=xOrVHYdzLA3QuZyvjQFcfMG6MRVAUrdl
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=project
      - REDIS_CONNECTION=local
      - REDIS_HOST=redis
      - S3_KEY=FAKE_S3
      - S3_SECRET=FAKE_S3_key
      - S3_BUCKET=app-pics
      - S3_REGION=
      - S3_ENDPOINT=http://minio:9000
    command: sh -c './wait-for-db.sh database:3306 -- adonis migration:run && adonis serve --dev -p'

  database:
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=project

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=FAKE_S3
      - MINIO_SECRET_KEY=FAKE_S3_key
    volumes:
      - minio_data:/export
      # - /mnt/export:/export
      # - /mnt/config:/root/.minio
    entrypoint: sh
    command: -c 'mkdir -p /export/app-pics && /usr/bin/minio server /export'

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 FAKE_S3 FAKE_S3_key;
      /usr/bin/mc mb myminio/app-pics;
      /usr/bin/mc policy download myminio/app-pics;
      exit 0;
      "

  nginx:
    volumes:
      - ./nginx/nginx-app.template:/etc/nginx/conf.d/nginx-app.template
      - ./nginx/certs:/etc/ssl/certs

volumes:
  minio_data: